# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  config.vm.box = "parallels/centos-7.1"

  config.vm.network "private_network", ip: "192.168.33.11"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../../playbooks/sites.yml"
    ansible.inventory_path = "../../playbooks/hosts"
    ansible.limit = "frequency"
  end

end
